### PR TITLE
credit_card_validations.gemspec - update activemodel && activesupport…

### PR DESCRIPTION
**Pull request by ninp0**
… to support <= 7.1

### CODE REVIEW

**Comment by ninp0** [comment]
Please merge to support activemodel && activesupportt <= 7.1 and release a new gem version at your earliest convenience.  Thanks in advance!

**Comment by ninp0** [comment]
Please release an updated gem at your earliest convenience.  Thanks @Fivell for merging so quickly.

**Comment by jscheid** [comment]
@ninp0 this change isn't ideal because ([surprisingly](https://jubianchi.github.io/semver-check/#/%3C%3D%207.1/7.1.1)) `<= 7.1` doesn't match `7.1.1` in Ruby land:

```
[1] pry(main)> Semantic::Version.new('7.1.1').satisfies?('<= 7.1')
=> false
```

Please could you change it to `< 7.2` so that we can use it with Rails 7.1.1 and future 7.1 patches?

**Comment by ninp0** [comment]
@jscheid PR submitted here: didww/credit_card_validations/pull/124

**Comment by jscheid** [comment]
Ah just saw #123 is the same.

**Pull request merged**
