### PR TITLE
mastercard 50 prefix and doc

### PR DESCRIPTION
**Pull request by Chucheen**
Added the rule for a card that starts with 50 for mastercard. As well as adding documentation for when devs want to add only a rule to a brand

### CODE REVIEW

**Comment by Fivell** [comment]
@Chucheen , thanks PR is blocked by failing tests on travis

**Comment by Chucheen** [comment]
@Fivell This is a bit trivial as it is failing because Dankort's cards starts with 50 (5019), should i go ahead and a fix for this so the regex generator can have a negative lookahead for similar rules (like in this case)?

**Comment by Fivell** [comment]
@Chucheen , not only Dankort's, but Elo and Maestro as well, And actually I don't see reason why this rule should be added for mastercard

**Comment by Fivell** [comment]
@Chucheen , also 50111 that was mentioned in docs, is more about Maestro , not Mastercard

**Comment by Chucheen** [comment]
Thankyou @Fivell 
Then i propose 2 things here:
1.- When a rule is added, verify if it has conflicts with other prefixes. If not then just add the regex as right now, if not assign a regex that is not going to have conflict with the others.

2.- Be able to accept another path for the data. If it's provided use it, otherwise use the Gem's one.

I like the first one more.

**Comment by Fivell** [comment]
@Chucheen, how do you want to verify prefix ?

**Comment by Fivell** [comment]
closed as obsolete

**Pull request closed without merging**
