### PR TITLE
Add Discover card prefixes

### PR DESCRIPTION
**Pull request by BerntWinqvist**
We've had customers with Discover credit cards starting with 6011 49...
I'm not sure if there are more prefixes that's uncovered, but this is a start.

Edit: I've updated the PR according to Barclays documentation: https://www.barclaycard.co.uk/content/dam/barclaycard/documents/business/accepting-payments/bin-rules-uk.pdf

I'm not sure if there is an issue with the overlap between Diners Club and Discover. (300-205, 36 & 38)

### CODE REVIEW

**Comment by jnwaletzko** [comment]
@Fivell would it be possible to get a new gem version with this change in it? It would help me a lot!

**Comment by danigirl329** [comment]
Same, @Fivell we are running into this issue with our customers now as well and would like to get this updated. Thanks for all you do on this gem!

**Comment by danigirl329** [comment]
@Fivell Bumping this - this has come up again for us. Are you able to deploy?

**Comment by Fivell** [comment]
@danigirl329  @jnwaletzko https://rubygems.org/gems/credit_card_validations/versions/6.0.0

**Comment by Fivell** [comment]
@danigirl329  please check this https://github.com/didww/credit_card_validations#configuration, this will allow you to  keep own rules in local repository so you do not need to wait for new version

**Pull request merged**
